def credential = 'Mejik'
def server = 'sgnd@192.168.3.174'
def dir = '~/test-ade/dumbflix-frontend'

pipeline{
    agent any
    stages{
        stage("Checkout Code") {
           steps {
               checkout scm
           }
       }
        stage('Pull test experimental'){
            steps{
                sshagent([credential]){
                    sh """ssh -o StrictHostKeyChecking=no ${server} << EOF
                    cd ${dir}
                    git config --local user.email muhamaddestar5@gmail.com
                    git config --local user.name ademuh
		    git remote set-url origin git@github.com:ademuh/dumbflix-frontend.git
                    git pull origin ${env.BRANCH_NAME}
		    echo "My balls in your development"
                    exit
                    EOF"""
                    }
                }
            }
        }
    }
